package ServerOperationApp;


/**
* ServerOperationApp/ServerOperationIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerOperationIDL.idl
* Friday, June 8, 2018 4:19:55 PM EDT
*/

public interface ServerOperationIDL extends ServerOperationIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerOperationIDL
